version: '2'
services:
    myjir-app:
        image: myjir
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://myjir-postgresql:5432/myJiR
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myjir-postgresql:
        extends:
            file: postgresql.yml
            service: myjir-postgresql
